# Generated by Django 4.0.5 on 2022-06-25 08:38

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200824_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='item',
            name='labels',
            field=models.CharField(blank=True, choices=[('BestSeller', 'BestSeller'), ('New', 'New'), ('Coming Soon', 'Coming Soon')], max_length=25),
        ),
    ]
