# Generated by Django 4.0.5 on 2022-06-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_vid_alter_reviews_options_alter_item_labels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vid',
        ),
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='keys',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(),
        ),
    ]
